#define PREFIX HEDES
#define COMPONENT MISSIONMODULES
#define RECOMPILE
#define DEBUG_MODE_FULL

#include "\a3\ui_f\hpp\definecommongrids.inc"
#include "\x\cba\addons\main\script_macros_common.hpp"

#define HEDESGUI_MISSIONDIALOG_BACKGROUND    10001
#define HEDESGUI_MISSIONDIALOG_OKBTN         10002
#define HEDESGUI_MISSIONDIALOG_CANCELBTN     10003
#define HEDESGUI_MISSIONDIALOG_AVATAR        10004
#define HEDESGUI_MISSIONDIALOG_NAME          10005
#define HEDESGUI_MISSIONDIALOG_DIALOG        10006
#define HEDESGUI_MISSIONDIALOG_TITLEBAR      10007
#define HEDESGUI_MISSIONDIALOG_LISTBOX       10008
#define HEDESGUI_MISSIONDIALOG_DESCRIPTION   10009
#define HEDESGUI_MISSIONDIALOG_BACKGROUND2   10010