#include "\a3\ui_f\hpp\definecommongrids.inc"
#define GUI_TEXT_SIZE_SMALL 	(GUI_GRID_H * 0.8)
#define GUI_TEXT_SIZE_MEDIUM 	(GUI_GRID_H * 1)
#define GUI_TEXT_SIZE_LARGE 	(GUI_GRID_H * 1.2)

#define HEDESGUI_MISSIONDIALOG_BACKGROUND    10001
#define HEDESGUI_MISSIONDIALOG_OKBTN         10002
#define HEDESGUI_MISSIONDIALOG_CANCELBTN     10003
#define HEDESGUI_MISSIONDIALOG_AVATAR        10004
#define HEDESGUI_MISSIONDIALOG_NAME          10005
#define HEDESGUI_MISSIONDIALOG_DIALOG        10006
#define HEDESGUI_MISSIONDIALOG_TITLEBAR      10007
#define HEDESGUI_MISSIONDIALOG_LISTBOX       10008
#define HEDESGUI_MISSIONDIALOG_DESCRIPTION   10009
#define HEDESGUI_MISSIONDIALOG_BACKGROUND2   10010
